services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: kcloud_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  filestorage:
    build:
      context: .
      dockerfile: KCloud.FileStorage/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Storage__Path: /app/files
      JWT__Key: "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"
    volumes:
      - file-storage:/app/files
    ports:
      - "5002:8080"
      
  auth:
    build:
      context: .
      dockerfile: KCloud.Auth/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      SQLite__DBPath: /app/data/auth.db
      JWT__Key: "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"
    volumes:
      - auth-data:/app/data
    ports:
      - "5003:8080"
      
  gateway:
    build:
      context: .
      dockerfile: KCloud.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5178:8080"
      
  web:
    build:
      context: .
      dockerfile: KCloud.Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      FileMetadata__Url: http://filemetadata:8080
      FileStorage__Url: http://filestorage:8080
      Auth__Url: http://auth:8080
      JWT__Key: "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"
    depends_on:
      - filemetadata
      - filestorage
      - auth
    ports:
      - "5005:8080"
      
  filemetadata:
    build:
      context: .
      dockerfile: KCloud.FileMetadata/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__FileMetadataDB: Host=postgres;Database=kcloud_db;Username=postgres;Password=Password123
      JWT__Key: "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"
    depends_on:
      - postgres
    ports:
      - "5001:8080"

volumes:
  postgres-data:
  file-storage:
  auth-data: