# Clean Railway configuration - one environment per service

# Web Environment
[environments.web.build]
builder = "dockerfile"
dockerfilePath = "KCloud/KCloud.Web/Dockerfile"

[environments.web.deploy]
startCommand = ""
restartPolicyType = "never"

[environments.web.variables]
ASPNETCORE_ENVIRONMENT = "Production"
Gateway__Url = "http://aware-curiosity.railway.internal"
JWT__Key = "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"

# Auth Environment
[environments.auth.build]
builder = "dockerfile"
dockerfilePath = "KCloud/KCloud.Auth/Dockerfile"

[environments.auth.deploy]
startCommand = ""
restartPolicyType = "never"

[environments.auth.variables]
ASPNETCORE_ENVIRONMENT = "Production"
SQLite__DBPath = "/app/data/auth.db"
JWT__Key = "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"

# Gateway Environment
[environments.gateway.build]
builder = "dockerfile"
dockerfilePath = "KCloud/KCloud.Gateway/Dockerfile"

[environments.gateway.deploy]
startCommand = ""
restartPolicyType = "never"

[environments.gateway.variables]
ASPNETCORE_ENVIRONMENT = "Production"
Auth__Url = "http://aware-curiosity.railway.internal"
FileStorage__Url = "http://aware-curiosity.railway.internal"
FileMetadata__Url = "http://aware-curiosity.railway.internal"
JWT__Key = "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"

# FileStorage Environment
[environments.filestorage.build]
builder = "dockerfile"
dockerfilePath = "KCloud/KCloud.FileStorage/Dockerfile"

[environments.filestorage.deploy]
startCommand = ""
restartPolicyType = "never"

[environments.filestorage.variables]
ASPNETCORE_ENVIRONMENT = "Production"
Storage__Path = "/app/files"
JWT__Key = "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"

# FileMetadata Environment
[environments.filemetadata.build]
builder = "dockerfile"
dockerfilePath = "KCloud/KCloud.FileMetadata/Dockerfile"

[environments.filemetadata.deploy]
startCommand = ""
restartPolicyType = "never"

[environments.filemetadata.variables]
ASPNETCORE_ENVIRONMENT = "Production"
ConnectionStrings__FileMetadataDB = "${{DATABASE_URL}}"
JWT__Key = "13f975f45c32948d5ab2e2a29d53d6a56b9569a9c8f8cd75d2e456ee7dedb69ee19836d25081c2c11880d58e4d494eb3010fecccabdb9ffa82b50d1b43f47641"